/**
 * Builds the editor's `dist/styles.css`.
 *
 * Tailwind v4 has no `important: '.ep-root'` selector-scoping (the v3 mechanism
 * that kept the embedded editor's utilities winning inside `.ep-root` without
 * leaking into the host app). We reconstruct it in two steps:
 *
 *   1. Generate utilities-only CSS with the Tailwind v4 CLI (no preflight, so
 *      the host app isn't reset) from `src/styles/_tailwind.css`.
 *   2. Scope every generated *utility rule* under `.ep-root`, while leaving the
 *      global bits (`:root`/`:host` theme vars, `@property`, `@keyframes`, the
 *      `@layer properties` reset) at the top level where they must stay.
 *
 * The result is concatenated after the editor chrome
 * (docx-editor-core/src/styles/editor.css — plain CSS) into dist/styles.css.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(here, '..');

const tailwindInput = join(pkgRoot, 'src/styles/_tailwind.css');
const chromeInput = join(pkgRoot, '../docx-editor-core/src/styles/editor.css');
const distDir = join(pkgRoot, 'dist');
const outFile = join(distDir, 'styles.css');
const tmpFile = join(distDir, '.tw-utilities.tmp.css');
const cli = join(pkgRoot, 'node_modules/.bin/tailwindcss');

if (!existsSync(distDir)) mkdirSync(distDir, { recursive: true });

// 1. Generate utilities-only CSS.
execFileSync(cli, ['-i', tailwindInput, '-o', tmpFile], { stdio: 'inherit' });
const generated = readFileSync(tmpFile, 'utf8');
rmSync(tmpFile, { force: true });

// 2. Scope utility rules under `.ep-root`.
const scoped = scopeUnderEpRoot(generated);

// 3. Concatenate chrome + scoped utilities.
const chrome = readFileSync(chromeInput, 'utf8');
const banner =
  '/* Generated by scripts/build-css.mjs — editor chrome + .ep-root-scoped Tailwind v4 utilities. Do not edit. */\n';
writeFileSync(outFile, `${banner}\n${chrome}\n\n${scopeBanner()}\n${scoped}\n`);

console.log(`Wrote ${outFile}`);

function scopeBanner() {
  return '/* ---- Tailwind v4 utilities, scoped under .ep-root ---- */';
}

/**
 * Walks top-level blocks. Rule blocks (selector `{ … }`) get every selector in
 * their list prefixed with `.ep-root `. At-rules (`@property`, `@keyframes`,
 * `@layer …`, `@media …`) and the `:root, :host` theme-var block are emitted
 * verbatim — they must stay global. Nested rules (`&:hover`, `@media` inside a
 * utility) ride along inside the prefixed parent untouched.
 */
function scopeUnderEpRoot(css) {
  const out = [];
  let i = 0;
  const n = css.length;

  while (i < n) {
    // Preserve comments verbatim.
    if (css[i] === '/' && css[i + 1] === '*') {
      const end = css.indexOf('*/', i + 2);
      const stop = end === -1 ? n : end + 2;
      out.push(css.slice(i, stop));
      i = stop;
      continue;
    }
    // Whitespace between blocks.
    if (/\s/.test(css[i])) {
      out.push(css[i]);
      i++;
      continue;
    }
    // Read a header up to the next `{` or `;` at this depth.
    let j = i;
    while (j < n && css[j] !== '{' && css[j] !== ';') j++;

    if (j >= n) {
      out.push(css.slice(i));
      break;
    }

    if (css[j] === ';') {
      // A statement (e.g. `@layer properties;`). Emit verbatim.
      out.push(css.slice(i, j + 1));
      i = j + 1;
      continue;
    }

    // css[j] === '{' — find the matching close brace.
    const header = css.slice(i, j).trim();
    const bodyStart = j;
    let depth = 0;
    let k = j;
    for (; k < n; k++) {
      if (css[k] === '{') depth++;
      else if (css[k] === '}') {
        depth--;
        if (depth === 0) break;
      }
    }
    const block = css.slice(bodyStart, k + 1); // includes the braces

    const isAtRule = header.startsWith('@');
    const isThemeVars = /^:root\b|:host\b/.test(header);

    if (isAtRule || isThemeVars) {
      out.push(`${header}${block}`);
    } else {
      const scopedHeader = header
        .split(',')
        .map((sel) => `.ep-root ${sel.trim()}`)
        .join(',\n');
      out.push(`${scopedHeader}${block}`);
    }
    i = k + 1;
  }

  return out.join('');
}
