// Generates packages/shared/src/patrick-docs.generated.ts — the docs concatenated
// into one Markdown string, compiled into the app so the agent's patrick_help tool
// can serve them (the sidecar binary can't read files from disk at runtime).
// Run with `pnpm gen:docs`; re-run when the docs change.

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Resolve from the script's own location so it runs from any cwd (the apps/api
// build, not just the repo root).
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DOCS_DIR = path.join(ROOT, "apps/site/content/docs");
const OUT = path.join(ROOT, "packages/shared/src/patrick-docs.generated.ts");

async function walk(dir: string): Promise<string[]> {
	const out: string[] = [];
	for (const e of await fs.readdir(dir, { withFileTypes: true })) {
		const full = path.join(dir, e.name);
		if (e.isDirectory()) out.push(...(await walk(full)));
		else if (e.name.endsWith(".mdx")) out.push(full);
	}
	return out;
}

function parse(input: string): { title: string; order: number; body: string } {
	const raw = input.replace(/\r\n/g, "\n"); // tolerate CRLF checkouts
	const m = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
	const front = m?.[1] ?? "";
	const body = (m?.[2] ?? raw).trim();
	const title = (front.match(/^title:\s*(.+)$/m)?.[1] ?? "Untitled").trim();
	const order = Number(front.match(/^order:\s*(.+)$/m)?.[1] ?? 99);
	return { title, order, body };
}

async function main() {
	const files = await walk(DOCS_DIR);
	// Skip section-index stubs — a folder index.mdx that has sibling pages is a
	// nav label, not content (the root index.mdx, Welcome, has no .mdx siblings).
	const isSectionIndex = (f: string) =>
		path.basename(f) === "index.mdx" &&
		files.some((o) => o !== f && path.dirname(o) === path.dirname(f));

	const docs = (
		await Promise.all(
			files
				.filter((f) => !isSectionIndex(f))
				.map(async (f) => ({ f, ...parse(await fs.readFile(f, "utf8")) })),
		)
	)
		.filter((d) => d.body)
		.sort((a, b) => a.order - b.order || a.f.localeCompare(b.f));

	const md = docs.map((d) => `# ${d.title}\n\n${d.body}`).join("\n\n---\n\n");
	const out = `// GENERATED by scripts/gen-patrick-docs.ts — DO NOT EDIT. Run \`pnpm gen:docs\`.
// The Patrick docs as one Markdown string, served by the agent's patrick_help tool.

export const PATRICK_DOCS = ${JSON.stringify(md)};
`;
	await fs.writeFile(OUT, out);
	console.log(`gen:docs → ${docs.length} docs, ${md.length} chars`);
}

main();
