/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsFrontendRouteImport } from './routes/docs/frontend'
import { Route as DocsDesktopRouteImport } from './routes/docs/desktop'
import { Route as DocsDatabaseRouteImport } from './routes/docs/database'
import { Route as DocsArchitectureRouteImport } from './routes/docs/architecture'
import { Route as DocsApiRouteImport } from './routes/docs/api'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFrontendRoute = DocsFrontendRouteImport.update({
  id: '/frontend',
  path: '/frontend',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDesktopRoute = DocsDesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDatabaseRoute = DocsDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => DocsRoute,
} as any)
const DocsArchitectureRoute = DocsArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/api': typeof DocsApiRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/database': typeof DocsDatabaseRoute
  '/docs/desktop': typeof DocsDesktopRoute
  '/docs/frontend': typeof DocsFrontendRoute
  '/docs/': typeof DocsIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/database': typeof DocsDatabaseRoute
  '/docs/desktop': typeof DocsDesktopRoute
  '/docs/frontend': typeof DocsFrontendRoute
  '/docs': typeof DocsIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/api': typeof DocsApiRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/database': typeof DocsDatabaseRoute
  '/docs/desktop': typeof DocsDesktopRoute
  '/docs/frontend': typeof DocsFrontendRoute
  '/docs/': typeof DocsIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/api'
    | '/docs/architecture'
    | '/docs/database'
    | '/docs/desktop'
    | '/docs/frontend'
    | '/docs/'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/api'
    | '/docs/architecture'
    | '/docs/database'
    | '/docs/desktop'
    | '/docs/frontend'
    | '/docs'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/api'
    | '/docs/architecture'
    | '/docs/database'
    | '/docs/desktop'
    | '/docs/frontend'
    | '/docs/'
    | '/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/frontend': {
      id: '/docs/frontend'
      path: '/frontend'
      fullPath: '/docs/frontend'
      preLoaderRoute: typeof DocsFrontendRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/desktop': {
      id: '/docs/desktop'
      path: '/desktop'
      fullPath: '/docs/desktop'
      preLoaderRoute: typeof DocsDesktopRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/database': {
      id: '/docs/database'
      path: '/database'
      fullPath: '/docs/database'
      preLoaderRoute: typeof DocsDatabaseRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/architecture': {
      id: '/docs/architecture'
      path: '/architecture'
      fullPath: '/docs/architecture'
      preLoaderRoute: typeof DocsArchitectureRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsApiRoute: typeof DocsApiRoute
  DocsArchitectureRoute: typeof DocsArchitectureRoute
  DocsDatabaseRoute: typeof DocsDatabaseRoute
  DocsDesktopRoute: typeof DocsDesktopRoute
  DocsFrontendRoute: typeof DocsFrontendRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsApiRoute: DocsApiRoute,
  DocsArchitectureRoute: DocsArchitectureRoute,
  DocsDatabaseRoute: DocsDatabaseRoute,
  DocsDesktopRoute: DocsDesktopRoute,
  DocsFrontendRoute: DocsFrontendRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
